import streamlit as st

st.set_page_config(page_title="Legal | CrestCV Privacy & Terms", page_icon="⚖️")

st.title("⚖️ Legal & Privacy Information")
st.caption("Effective Date: April 2026")

# Using tabs to keep it clean for the user but readable for Google bots
tab1, tab2 = st.tabs(["🔒 Privacy Policy", "📄 Terms of Service"])

with tab1:
    st.header("Privacy Policy")
    
    st.subheader("1. Information Collection")
    st.write("""
    At **CrestCV**, we collect information to provide better services to our users. This includes:
    - **Personal Information:** Name, email, and professional history provided by you while using the Resume Builder.
    - **Usage Data:** Information about how you use our website, including your IP address and browser type.
    """)

    st.subheader("2. Google AdSense & Cookies")
    st.warning("Important for our visitors:")
    st.write("""
    - Google, as a third-party vendor, uses cookies to serve ads on CrestCV.
    - Google's use of the **DART cookie** enables it to serve ads to our users based on their visit to our site and other sites on the Internet.
    - Users may opt out of the use of the DART cookie by visiting the [Google Ad and Content Network privacy policy](https://policies.google.com/technologies/ads).
    """)

    st.subheader("3. Data Security")
    st.write("We do not store your uploaded PDF files permanently. Files processed by our AI Resume Analyzer are deleted after the session expires.")

with tab2:
    st.header("Terms of Service")
    
    st.subheader("1. Acceptance of Terms")
    st.write("By using CrestCV, you agree to comply with and be bound by these terms. If you do not agree, please do not use our services.")

    st.subheader("2. AI Disclaimer")
    st.write("""
    CrestCV utilizes Large Language Models (AI) to generate career suggestions. 
    - We do not guarantee employment or interview calls.
    - Users are responsible for verifying the accuracy of AI-generated content before submitting it to employers.
    """)

    st.subheader("3. Intellectual Property")
    st.write("The resumes generated by you belong to you. However, the design templates and code used by CrestCV remain the intellectual property of the developer.")

st.divider()
st.markdown("### Contact Us")
st.write("If you have any questions about these Legal Terms, please reach out to: **sreenandhvnair5@gmail.com**")
